version: "3.9"

services:
  defi_stats:
    container_name: api
    env_file:
      - ./api/.env
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./api:/home/komodian/api
    ports:
      - 127.0.0.1:7068:7068
    depends_on:
      - pgsqldb
      - mm2_8762
      - memcached
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    restart: always
    command: ["poetry", "run", "python", "main.py"]

  mm2_8762:
    container_name: mm2_8762
    env_file:
      - ./mm2_8762/.env
    build:
      context: ./mm2_8762
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./mm2_8762:/home/komodian/mm2
    ports:
      - 127.0.0.1:7862:7862
      - 127.0.0.1:42946:42845
      - 127.0.0.1:42956:42855
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    restart: always

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "127.0.0.1:11211:11211"
    restart: always
    depends_on:
      - pgsqldb
    command: ["memcached", "-I", "10m"]

  pgsqldb:
    container_name: pgsqldb
    image: postgres:12.17
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./api/.env
    depends_on:
      - mm2_8762
    ports:
      - "127.0.0.1:5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

volumes:
  pg_data:
