version: "3.9"

services:
  komodefi:
    container_name: mm2
    env_file:
      - ./mm2/.env
    build:
      context: ./mm2
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./mm2:/home/komodian/mm2
    ports:
      - 127.0.0.1:7877:7877
      - 127.0.0.1:38901:38900
      - 127.0.0.1:38891:38890
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    restart: always

  komodefi_8762:
    container_name: mm2_8762
    env_file:
      - ./mm2_8762/.env
    build:
      context: ./mm2_8762
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./mm2_8762:/home/komodian/mm2
    ports:
      - 127.0.0.1:7862:7862
      - 127.0.0.1:42946:42845
      - 127.0.0.1:42956:42855
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    restart: always
